apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: backend-apis
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: kevinshelaga/kafka-consumer:7-alpine